<div id="main" role="main">
	<p>
		I generate my website on my computer with gnu make using this makefile. it gives me all the dev conveniences I'd get from a templating engine or mvc framework but lets me serve plain documents without javascript from a traditional webserver. <code>while true; do make; sleep 2; done</code>, and it only ever builds what it needs to.
	</p>

	<p>
		it builds most pages by stitching files into templates, inserting and changing text and links here and there. it builds <i>this</i> page by inserting <i>itself</i> into a template, making it its own dependency, which has a few interesting consequences. this was the first time, for instance, I had to change a regex's pattern to stop it from matching a copy of itself. it also means this page will always have the current version of the makefile because it watches itself to see if it's newer than this page.
	</p>

	<p>
		I really like make. vi, sed, screen, I tend to gravitate towards tools older than I am. they're the survivors. I actually do like javascript, and I write a lot of it. but I think the web would be better if it were the exception rather than the rule. "back in my day, when we used the hypertext transfer protocol, we sent hypertext over it!" yadda yadda.
	</p>

	<p>
		I could have used a static site generator, I hear there are several good ones. but this is just so much more <i>fun</i>.
	</p>

	<pre>
		<code>
			xMAKEFILE
		</code>
	</pre>
</div>
