<div id="main" role="main">
	<p>
		I generate this website on my computer with this makefile. it gives me all the dev conveniences I'd get from a templating engine or mvc framework but lets me serve plain html/css from a traditional webserver. <code>while true; do make; sleep 2; done</code>, and it only ever builds what it needs to.
	</p>

	<p>
		it builds most pages by stitching files into templates, inserting and changing text and links here and there. it builds <i>this</i> page by inserting <i>itself</i> into a template, making it its own dependency, which has a few interesting consequences. this was the first time, for instance, I had to change a regex's pattern to stop it from matching a copy of itself. it also means this page will always have the current version of the makefile because it watches itself to see if it's newer than this page.
	</p>

	<p>
		I really like make. vi, sed, screen, I tend to gravitate toward tools older than I am. they're the survivors. I don't dislike javascript, and I write a lot of it in my day-to-day. but I think the web would be better if sites asking to execute code on the user's machine were the exception rather than the rule. "when I was your age, we used the hypertext transfer protocol to send hypertext, dammit!" yadda yadda.
	</p>

	<p>
		I could have used a static site generator, I hear there are several good ones. but this is just so much more <i>fun</i>.
	</p>

	<pre>
		<code>
			xMAKEFILE
		</code>
	</pre>
</div>
